### PR TITLE
change module name to use `_` instead of `-`.

### LINKED ISSUE #2: C-1.1.23 is failing when it should not be
I have a failing test for control 1.1.23: Disable USB Storage. 
```
  ×  C-1.1.23: Disable USB Storage (1 failed)
     ✔  Kernel Module usb-storage is expected not to be loaded
     ×  Kernel Module usb-storage is expected to be disabled
     expected `Kernel Module usb-storage.disabled?` to be truthy, got false
```

However, the 'check' commands indicate that this should not fail:
```
~ $ modprobe -n -v usb-storage
install /bin/true
~ $ lsmod | grep usb-storage
```

The other disabled module checks are working as expected. Could this have to do with the fact that there is a hyphen in the name of the module? Looking at the [`disabled?`](https://github.com/inspec/inspec/blob/49b7d1033dcee2133be4a5f25490174b09cc83e6/lib/inspec/resources/kernel_module.rb#L59-L61) check, it seems that it runs `modprobe --showconfig`, which returns the following line (among others): 

```
install usb_storage /bin/true
```

Note the `_`, instead of the `-` that the docs for this control mention (and the official CIS Benchmark PDF also uses `-` when discussing this control). Are the `-` and `_` interchangeable here? Should the inspec `kernel_module` constructor use the `_` form?

### PR DESCRIPTION
**Pull request by pkaeding**
Fixes #2

This seems to work in my environment, at least :).

### CODE REVIEW

**Comment by aaronlippold** [comment]
Everything looks good except for the default tag set for CIS profiles. For a CIS benchmark profile and all profiles, we try not to add data that is not part of the baseline, except for data that we can 'derive' - such as the NIST tag alignment from the CIS CDC tag.

https://saf.mitre.org/#/normalize 

```
  impact 0.7
  tag severity: 'high'
  tag nist: ["CM-6"]
  tag cis_scored: true
  tag cis_version: 1.2.0
  tag cis_level: 3
  tag cis_controls: ["5.1"]
  tag cis_cdc_version: 7
  tag cis_rid: "1.1.1.1"
```
Please update your PR to follow the above so we don't mix STIG tags with CIS tags.

**Review by aaronlippold — CHANGES_REQUESTED** [review]
https://saf.mitre.org/#/normalize 

```
  impact 0.7
  tag severity: 'high'
  tag nist: ["CM-6"]
  tag cis_scored: true
  tag cis_version: 1.2.0
  tag cis_level: 3
  tag cis_controls: ["5.1"]
  tag cis_cdc_version: 7
  tag cis_rid: "1.1.1.1"
```
Please update your PR to follow the above so we don't mix STIG tags with CIS tags.

**Review by aaronlippold — CHANGES_REQUESTED** [review]
Updated PR for an example and noted where we are trying to document the HDF style guide.

**Comment by pkaeding** [comment]
Okay, thanks for making those tag/style changes. Is there anything else you'd like me to change?

**Review by aaronlippold — APPROVED** [review]

**Pull request merged**
